#include "BIS_AddonInfo.hpp"
class cfgMods
{
	class Mod_Base;
	class Indonesian_Mod: Mod_Base
	{
		logo="\tni\TNI.paa";
	};
	author="Habib Menye";
	timepacked="1506738193";
};
class CfgPatches
{
	class TNI_config
	{
		units[]=
		{
			"tniWd_Soldier",
			"tniWd_GL",
			"tniWd_MG",
			"tniWd_AA",
			"tniWd_AT",
			"tniWd_Medic",
			"tniWd_RifAT",
			"tniWd_Mrk",
			"tniWd_TL",
			"tniKop_Soldier",
			"tniKop_GL",
			"tniKop_MG",
			"tniKop_AA",
			"tniKop_AT",
			"tniKop_Medic",
			"tniKop_RifAT",
			"tniKop_Mrk",
			"tniKop_TL",
			"tniSka_Soldier",
			"tniSka_GL",
			"tniSka_MG",
			"tniSka_AA",
			"tniSka_AT",
			"tniSka_Medic",
			"tniSka_RifAT",
			"tniSka_Mrk",
			"tniSka_TL",
			"B_Soldier_VR_F",
			"O_Soldier_VR_F",
			"I_Soldier_VR_F",
			"C_Soldier_VR_F",
			"B_Protagonist_VR_F",
			"O_Protagonist_VR_F",
			"I_Protagonist_VR_F",
			"headgear_H_Booniehat_oli",
			"headgear_H_Bandanna_surfer_blk",
			"headgear_H_Bandanna_surfer_grn",
			"headgear_H_Bandanna_blu",
			"headgear_H_Watchcap_cbr",
			"headgear_H_Cap_usblack",
			"headgear_H_Bandanna_sand",
			"headgear_H_Cap_surfer",
			"headgear_H_Cap_police",
			"Item_U_IG_Guerrilla_6_1",
			"Item_U_BG_Guerrilla_6_1",
			"Item_U_OG_Guerrilla_6_1"
		};
		weapons[]=
		{
			"U_BG_Guerrilla_6_1",
			"U_OG_Guerrilla_6_1",
			"U_IG_Guerrilla_6_1",
			"U_B_Protagonist_VR",
			"U_O_Protagonist_VR",
			"U_I_Protagonist_VR",
			"U_B_Soldier_VR",
			"U_O_Soldier_VR",
			"U_I_Soldier_VR",
			"U_C_Soldier_VR",
			"H_ShemagOpen_khk",
			"H_ShemagOpen_tan",
			"H_Booniehat_khk",
			"H_Booniehat_oli",
			"H_Booniehat_tan",
			"H_Bandanna_cbr",
			"H_Bandanna_gry",
			"H_Bandanna_khk",
			"H_Bandanna_sgg",
			"H_Bandanna_surfer",
			"H_Bandanna_camo",
			"H_Bandanna_surfer_blk",
			"H_Bandanna_surfer_grn",
			"H_Bandanna_blu",
			"H_Bandanna_sand",
			"H_Watchcap_khk",
			"H_Watchcap_camo",
			"H_Watchcap_cbr",
			"H_Cap_red",
			"H_Cap_tan",
			"H_Cap_grn",
			"H_Cap_blu",
			"H_Cap_grn_BI",
			"H_Cap_oli",
			"H_Cap_usblack",
			"H_Cap_surfer",
			"H_Cap_police",
			"H_Cap_tan_specops_US",
			"H_Cap_khaki_specops_UK",
			"H_MilCap_blue"
		};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Characters_F_BLUFOR",
			"A3_Characters_F_CIVIL",
			"A3_Data_F",
			"A3_Weapons_F",
			"A3_Characters_F"
		};
	};
};
class CfgFactionClasses
{
	class TNI_Forces
	{
		displayName="TNI Forces";
		priority=2;
		side=1;
		icon="\TNI\paa\TNI_icon.paa";
	};
};
class CfgVehicleClasses
{
	class TniWD_Unit
	{
		displayName="Men (TNI woodland)";
	};
	class Kopassus_Unit
	{
		displayName="Men (Kopassus)";
	};
	class Kopaska_Unit
	{
		displayName="Men (Kopaska)";
	};
};
class CfgGroups
{
	class West
	{
		side=1;
		class TNI_unit
		{
			name="TNI Forces";
			class Infantry
			{
				name="Infantry";
				class TNI_Inf_Squad
				{
					name="TNI WD Squad Team";
					side="West";
					faction="TNI_Forces";
					class Unit0
					{
						side=1;
						vehicle="tniWd_TL";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=1;
						vehicle="tniWd_Soldier";
						rank="SERGEANT";
						position[]={3,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="tniWd_GL";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="tniWd_RifAT";
						rank="";
						position[]={7,0,0};
					};
					class Unit4
					{
						side=1;
						vehicle="tniWd_MG";
						rank="";
						position[]={9,0,0};
					};
					class Unit5
					{
						side=1;
						vehicle="tniWd_AT";
						rank="";
						position[]={12,0,0};
					};
					class Unit6
					{
						side=1;
						vehicle="tniWd_AA";
						rank="";
						position[]={14,0,0};
					};
					class Unit7
					{
						side=1;
						vehicle="tniWd_Medic";
						rank="";
						position[]={16,0,0};
					};
					class Unit8
					{
						side=1;
						vehicle="tniWd_Mrk";
						rank="";
						position[]={18,0,0};
					};
				};
				class Kopassus_Inf_Squad
				{
					name="Kopassus Squad Team";
					side="West";
					faction="TNI_Forces";
					class Unit0
					{
						side=1;
						vehicle="tniKop_TL";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=1;
						vehicle="tniKop_Soldier";
						rank="SERGEANT";
						position[]={3,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="tniKop_GL";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="tniKop_RifAT";
						rank="";
						position[]={7,0,0};
					};
					class Unit4
					{
						side=1;
						vehicle="tniKop_MG";
						rank="";
						position[]={9,0,0};
					};
					class Unit5
					{
						side=1;
						vehicle="tniKop_AT";
						rank="";
						position[]={12,0,0};
					};
					class Unit6
					{
						side=1;
						vehicle="tniKop_AA";
						rank="";
						position[]={14,0,0};
					};
					class Unit7
					{
						side=1;
						vehicle="tniKop_Medic";
						rank="";
						position[]={16,0,0};
					};
					class Unit8
					{
						side=1;
						vehicle="tniKop_Mrk";
						rank="";
						position[]={18,0,0};
					};
				};
				class Kopaska_Inf_Squad
				{
					name="Kopaska Squad Team";
					side="West";
					faction="TNI_Forces";
					class Unit0
					{
						side=1;
						vehicle="tniSka_TL";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=1;
						vehicle="tniSka_Soldier";
						rank="SERGEANT";
						position[]={3,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="tniSka_GL";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="tniSka_RifAT";
						rank="";
						position[]={7,0,0};
					};
					class Unit4
					{
						side=1;
						vehicle="tniSka_MG";
						rank="";
						position[]={9,0,0};
					};
					class Unit5
					{
						side=1;
						vehicle="tniSka_AT";
						rank="";
						position[]={12,0,0};
					};
					class Unit6
					{
						side=1;
						vehicle="tniSka_AA";
						rank="";
						position[]={14,0,0};
					};
					class Unit7
					{
						side=1;
						vehicle="tniSka_Medic";
						rank="";
						position[]={16,0,0};
					};
					class Unit8
					{
						side=1;
						vehicle="tniSka_Mrk";
						rank="";
						position[]={18,0,0};
					};
				};
			};
		};
	};
};
class cfgVehicles
{
	class B_Soldier_F;
	class B_soldier_LAT_F;
	class B_Soldier_GL_F;
	class B_soldier_AR_F;
	class B_soldier_M_F;
	class B_soldier_AA_F;
	class B_soldier_AT_F;
	class B_medic_F;
	class B_Soldier_03_F;
	class B_soldier_repair_F;
	class B_soldier_exp_F;
	class B_Soldier_TL_F;
	class B_Soldier_base_F;
	class tniWD_Soldier: B_Soldier_F
	{
		author="ROG_Blue";
		_generalMacro="tniWD_Soldier";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Rifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_GL: B_Soldier_GL_F
	{
		author="ROG_Blue";
		_generalMacro="tniWd_GL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Grenadier";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_MG: B_soldier_AR_F
	{
		author="ROG_Blue";
		_generalMacro="tniWd_MG";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Autorifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_weap_m240b_usmc",
			"rhsusf_weap_m1911a1",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m240b_usmc",
			"rhsusf_weap_m1911a1",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_Hamr"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_AA: B_soldier_AA_F
	{
		author="ROG_Blue";
		_generalMacro="tniWd_AA";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Missile Specialist (AA)";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="Jos_aa";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_AT: B_soldier_AT_F
	{
		author="ROG_Blue";
		_generalMacro="Marinir_AT";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Missile Specialist (AT)";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="Jos_at";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_short_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_short_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AT",
			"Titan_AT",
			"Titan_AT",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AT",
			"Titan_AT",
			"Titan_AT",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_Medic: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniWd_Medic";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Combat Life Saver";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_WoodlandMed";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="Jos_medic";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit",
			"Medikit"
		};
		linkeditems[]=
		{
			"Jos_Medwood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit",
			"Medikit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Medwood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_RifAT: B_soldier_LAT_F
	{
		author="ROG_Blue";
		_generalMacro="tniWd_RifAT";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Rifleman AT";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"rhs_weap_M136",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"rhs_weap_M136",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_m136_mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_m136_mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_Mrk: B_soldier_M_F
	{
		author="ROG_Blue";
		_generalMacro="tniWd_Mrk";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Marksman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodland";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_weap_m14ebrri_leu",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m14ebrri_leu",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniWd_TL: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="Marinir_TL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="TniWD_Unit";
		displayName="TNI Team Leader";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Woodlandrolled";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_wood",
			"tni_Booniehat_woodland",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_Soldier: B_Soldier_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_Soldier";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Rifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"tni_Booniehat_kopassus",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_GL: B_Soldier_GL_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_GL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopassus Grenadier";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_MG: B_soldier_AR_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_MG";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Autorifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_weap_m240b_usmc",
			"rhsusf_weap_m1911a1",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m240b_usmc",
			"rhsusf_weap_m1911a1",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_Hamr"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_AA: B_soldier_AA_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_AA";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Missile Specialist (AA)";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="jos2_aa";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_AT: B_soldier_AT_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_AT";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Missile Specialist (AT)";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="jos2_at";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_short_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_short_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AT",
			"Titan_AT",
			"Titan_AT",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AT",
			"Titan_AT",
			"Titan_AT",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_Medic: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_Medic";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Combat Life Saver";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_KopassusMed";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="jos2_medic";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_med2",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_med2",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_RifAT: B_soldier_LAT_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_Repair";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Rifleman AT";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"rhs_weap_M136",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"rhs_weap_M136",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_m136_mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_m136_mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniKop_Mrk: B_soldier_M_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_Mrk";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Marksman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassus";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_weap_m14ebrri_leu",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m14ebrri_leu",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniKop_TL: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniKop_TL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopassus_Unit";
		displayName="Kopassus Team Leader";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopassusrolled";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopassus.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_Soldier: B_Soldier_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_Soldier";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Rifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_GL: B_Soldier_GL_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_GL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Grenadier";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit",
			"HandGrenade",
			"HandGrenade",
			"HandGrenade"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit",
			"HandGrenade",
			"HandGrenade",
			"HandGrenade"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_MG: B_soldier_AR_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_MG";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Autorifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_weap_m240b_usmc",
			"rhsusf_weap_m1911a1",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m240b_usmc",
			"rhsusf_weap_m1911a1",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_50Rnd_762x51",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit",
			"optic_Hamr"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_AA: B_soldier_AA_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_AA";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Missile Specialist (AA)";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="jos1_aa";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_AT: B_soldier_AT_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_AT";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Missile Specialist (AT)";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="jos1_at";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_short_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"launch_B_Titan_short_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AT",
			"Titan_AT",
			"Titan_AT",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"Titan_AT",
			"Titan_AT",
			"Titan_AT",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_Medic: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_Medic";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Combat Life Saver";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_KopaskaMed";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="jos1_medic";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_med1",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_med1",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_RifAT: B_soldier_LAT_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_RifAT";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Rifleman AT";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"rhs_weap_M136",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_compm4",
			"rhs_weap_M136",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_m136_mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_m136_mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_Mrk: B_soldier_M_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_Mrk";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Marksman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaska";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_weap_m14ebrri_leu",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_m14ebrri_leu",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m118_special_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhsusf_20Rnd_762x51_m62_Mag",
			"rhs_mag_an_m8hc",
			"rhs_mag_m67",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniSka_TL: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniSka_TL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Kopaska_Unit";
		displayName="Kopaska Team Leader";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Kopaskarolled";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	
	
	
	
	
	
	class tniUN_Soldier: B_Soldier_F
	{
		author="ROG_Blue";
		_generalMacro="tniUN_Soldier";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Unifil_Unit";
		displayName="Kontigen Garuda Rifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_Unifil";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_unifil.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniUN_TL: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniUN_TL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Unifil_Unit";
		displayName="Kontigen Garuda Team Leader";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_UN_Rolled";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_unifil.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vtan",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniUN_Medic: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniUN_Medic";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="Unifil_Unit";
		displayName="Kontigen Garuda Combat Life Saver";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_UN_Med";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_unifil.paa"
		};
		backpack="jos1_medic";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_med1",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_med1",
			"tni_Booniehat_kopaska",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	
	
	
	
	
	
	class tniAL_Soldier: B_Soldier_F
	{
		author="ROG_Blue";
		_generalMacro="tniAL_Soldier";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="AL_Unit";
		displayName="TNI AL Rifleman";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_AL";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_al.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"tni_Booniehat_kopassus",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class tniAL_TL: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniAL_TL";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="AL_Unit";
		displayName="TNI AL Team Leader";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_AL_rolled";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_al.paa"
		};
		backpack="";
		weapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4_m203s_acog_usmc",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_M585_white",
			"rhs_mag_m67"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_Vblk",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class tniAL_Medic: B_Soldier_TL_F
	{
		author="ROG_Blue";
		_generalMacro="tniAL_Medic";
		scope=2;
		side=1;
		faction="TNI_Forces";
		vehicleClass="AL_Unit";
		displayName="TNI AL Combat Life Saver";
		nakedUniform="U_BasicBody";
		uniformClass="TNI_AL_Med";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_al.paa"
		};
		backpack="jos2_medic";
		weapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_m4a1_grip_acog2_usmc_sup",
			"rhsusf_weap_m1911a1",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhsusf_mag_7x45acp_MHP",
			"rhs_mag_mk3a2",
			"rhs_mag_mk3a2",
			"rhs_mag_mk84",
			"Chemlight_green",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_red"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"Jos_med2",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"Jos_med2",
			"rhsusf_protech_helmet_rhino_ess",
			"G_Tactical_Clear",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
	};
	
	
	
	
	
	
	
	
	
	class B_Kitbag_mcamo;
	class B_Kitbag_Base;
	class Bag_Base;
	class ContainerSupply;
	class ThingX;
	class Jos_inf: B_Kitbag_Base
	{
		displayName="J.O.S WD";
		maximumLoad=300;
		picture="\tas\ui\wd.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\backpack_blk_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=3;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=2;
			};
			class _xx_Chemlight_green
			{
				magazine="Chemlight_green";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class jos_aa: B_Kitbag_Base
	{
		displayName="Backpack AA";
		maximumLoad=300;
		picture="\tas\ui\wd.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\backpack_blk_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
			class _xx_Titan_AA
			{
				magazine="Titan_AA";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class jos_AT: B_Kitbag_Base
	{
		displayName="Backpack  AT";
		maximumLoad=300;
		picture="\tas\ui\wd.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\backpack_blk_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
			class _xx_Titan_AT
			{
				magazine="Titan_AT";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class Jos_Medic: B_Kitbag_Base
	{
		displayName="Backpack Medic";
		maximumLoad=320;
		picture="\tas\ui\wd.paa";
		hiddenSelectionsTextures[]=
		{
			"\tas\paa\jos_me.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=8;
			};
		};
	};
	class Jos1_inf: B_Kitbag_Base
	{
		displayName="J.O.S WD";
		maximumLoad=300;
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_brwn_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=5;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=2;
			};
			class _xx_Chemlight_green
			{
				magazine="Chemlight_green";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class jos1_aa: B_Kitbag_Base
	{
		displayName="Backpack AA";
		maximumLoad=300;
		picture="\tas\ui\tan.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_brwn_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
			class _xx_Titan_AA
			{
				magazine="Titan_AA";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class jos1_AT: B_Kitbag_Base
	{
		displayName="Backpack  AT";
		maximumLoad=300;
		picture="\tas\ui\tan.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_brwn_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
			class _xx_Titan_AT
			{
				magazine="Titan_AT";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class Jos1_Medic: B_Kitbag_Base
	{
		displayName="Backpack Medic";
		maximumLoad=320;
		picture="\tas\ui\tan.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_brwn_med.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=8;
			};
		};
	};
	class Jos2_inf: B_Kitbag_Base
	{
		displayName="J.O.S WD";
		maximumLoad=300;
		picture="\tas\ui\blk.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_olv_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=5;
			};
			class _xx_SmokeShell
			{
				magazine="SmokeShell";
				count=2;
			};
			class _xx_Chemlight_green
			{
				magazine="Chemlight_green";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class jos2_aa: B_Kitbag_Base
	{
		displayName="Backpack AA";
		maximumLoad=300;
		picture="\tas\ui\blk.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_olv_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
			class _xx_Titan_AA
			{
				magazine="Titan_AA";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class jos2_AT: B_Kitbag_Base
	{
		displayName="Backpack  AT";
		maximumLoad=300;
		picture="\tas\ui\blk.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\fastpack_olv_co.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
			class _xx_Titan_AT
			{
				magazine="Titan_AT";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
	};
	class Jos2_Medic: B_Kitbag_Base
	{
		displayName="Backpack Medic";
		maximumLoad=320;
		picture="\tas\ui\blk.paa";
		hiddenSelectionsTextures[]=
		{
			"\tni\paa\hazard.paa"
		};
		class TransportMagazines
		{
			class _xx_rhs_mag_30Rnd_556x45_M855A1_Stanag
			{
				magazine="rhs_mag_30Rnd_556x45_M855A1_Stanag";
				count=2;
			};
		};
		class TransportItems
		{
			class _xx_Medikit
			{
				name="Medikit";
				count=1;
			};
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=8;
			};
		};
	};
};
class cfgWeapons
{
	class H_HelmetB;
	class UniformItem;
	class HeadgearItem;
	class ItemCore;
	class Vest_NoCamo_Base;
	class Uniform_Base: ItemCore
	{
	};
	class TNI_Woodland: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI woodland";
		picture="\TNI\paa\icons\icon_uniform_woodland.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniWD_Soldier";
			containerClass="Supply40";
			mass=75;
		};
	};
	class TNI_Kopaska: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI kopaska";
		picture="\TNI\paa\icons\icon_uniform_kopaska.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniSka_Soldier";
			containerClass="Supply40";
			mass=75;
		};
	};
	class TNI_Kopassus: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI kopassus";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniKop_Soldier";
			containerClass="Supply40";
			mass=75;
		};
	};
	
	
	
	
	
	class TNI_Unifil: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI Kontigen Garuda";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniUN_Soldier";
			containerClass="Supply40";
			mass=75;
		};
	};
	class TNI_AL: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI AL";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniAL_Soldier";
			containerClass="Supply40";
			mass=75;
		};
	};
	
	
	
	
	
	class TNI_Woodlandrolled: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI woodland rolled";
		picture="\TNI\paa\icons\icon_uniform_woodland.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_tni_flag.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniWd_TL";
			containerClass="Supply40";
			mass=40;
		};
	};
	class TNI_Kopaskarolled: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI kopaska rolled";
		picture="\TNI\paa\icons\icon_uniform_kopaska.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_kopaska.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniSka_TL";
			containerClass="Supply40";
			mass=40;
		};
	};
	class TNI_Kopassusrolled: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI kopassus rolled";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_al.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniKop_TL";
			containerClass="Supply40";
			mass=40;
		};
	};
	
	
	
	
	
	
	class TNI_UN_Rolled: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI Kontigen Garuda Rolled";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_Unifil"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniUN_TL";
			containerClass="Supply40";
			mass=40;
		};
	};
	class TNI_AL_Rolled: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI AL Rolled";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\clothing_al"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniAL_TL";
			containerClass="Supply40";
			mass=40;
		};
	};
	
	
	
	
	
	
	
	class TNI_KopassusMed: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI kopassus Medic";
		picture="\TNI\paa\icons\icon_uniform_kopassus.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniKop_Medic";
			containerClass="Supply40";
			mass=75;
		};
	};
	class TNI_KopaskaMed: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI Kopaska Medic";
		picture="\TNI\paa\icons\icon_uniform_kopaska.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniSka_Medic";
			containerClass="Supply40";
			mass=75;
		};
	};
	class TNI_WoodlandMed: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI Woodland Medic";
		picture="\TNI\paa\icons\icon_uniform_woodland.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniWd_Medic";
			containerClass="Supply40";
			mass=75;
		};
	};
	
	
	
	
	
	class TNI_UN_Med: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI Kontigen Garuda Medic";
		picture="\TNI\paa\icons\icon_uniform_woodland.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniUN_Medic";
			containerClass="Supply40";
			mass=75;
		};
	};
	class TNI_AL_Med: Uniform_Base
	{
		dlc="Indonesian_Mod";
		scope=2;
		displayName="TNI AL Combat Life Saver";
		picture="\TNI\paa\icons\icon_uniform_woodland.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="tniAL_Medic";
			containerClass="Supply40";
			mass=75;
		};
	};
	
	
	
	
	
	class TNI_bandana_woodland: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Bandana Woodland";
		picture="\TNI\paa\icons\icon_bandanna_woodland.paa";
		model="\A3\Characters_F\CIVIL\headgear_c_bandana1.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\bandana_tni.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\CIVIL\headgear_c_bandana1.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\bandana_tni.paa"
			};
		};
	};
	class TNI_bandana_kopaska: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Bandana Kopaska";
		picture="\TNI\paa\icons\icon_bandanna_kopaska.paa";
		model="\A3\Characters_F\CIVIL\headgear_c_bandana1.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\bandana_kopaska.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\CIVIL\headgear_c_bandana1.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\bandana_kopaska.paa"
			};
		};
	};
	class TNI_bandana_kopassus: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Bandana Kopassus";
		picture="\TNI\paa\icons\icon_bandanna_kopassus.paa";
		model="\A3\Characters_F\CIVIL\headgear_c_bandana1.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\bandana_kopassus.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\CIVIL\headgear_c_bandana1.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\bandana_kopassus.paa"
			};
		};
	};
	class TNI_cap_woodland: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Cap Woodland";
		picture="\TNI\paa\icons\icon_cap_woodland.paa";
		model="\A3\Characters_F\Common\capb.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\cap_tni.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\Common\capb.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\cap_tni.paa"
			};
		};
	};
	class TNI_cap_kopaska: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Cap Kopaska";
		picture="\TNI\paa\icons\icon_cap_kopaska.paa";
		model="\A3\Characters_F\Common\capb.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\cap_kopaska.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\Common\capb.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\cap_kopaska.paa"
			};
		};
	};
	class TNI_cap_kopassus: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Cap Kopassus";
		picture="\TNI\paa\icons\icon_cap_kopassus.paa";
		model="\A3\Characters_F\Common\capb.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\cap_kopassus.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\Common\capb.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\cap_kopassus.paa"
			};
		};
	};
	class TNI_office_cap_woodland: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Officer Cap Woodland";
		picture="\TNI\paa\icons\icon_cap_patrol_woodland.paa";
		model="\A3\Characters_F\Common\cappatrol.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\cappatrol_tni.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\Common\cappatrol.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\cappatrol_tni.paa"
			};
		};
	};
	class TNI_office_cap_kopaska: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Officer Cap Kopaska";
		picture="\TNI\paa\icons\icon_cap_patrol_kopaska.paa";
		model="\A3\Characters_F\Common\cappatrol.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\cappatrol_kopaska.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\Common\cappatrol.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\cappatrol_kopaska.paa"
			};
		};
	};
	class TNI_office_cap_kopassus: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Officer Cap Kopassus";
		picture="\TNI\paa\icons\icon_cap_patrol_kopassus.paa";
		model="\A3\Characters_F\Common\cappatrol.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\cappatrol_kopassus.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\Characters_F\Common\cappatrol.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\cappatrol_kopassus.paa"
			};
		};
	};
	class TNI_booniehat_woodland: H_HelmetB
	{
		scope=2;
		displayName="TNI Booniehat Woodland";
		model="\A3\Characters_F\Common\booniehat";
		picture="\TNI\paa\icons\icon_booniehat_woodland.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\bonniehat_tni.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=10;
			allowedSlots[]={801,901,701,605};
			uniformModel="\A3\Characters_F\Common\booniehat";
			hiddenSelections[]=
			{
				"camo"
			};
			modelSides[]={6};
			armor=1;
			passThrough=0;
		};
	};
	class TNI_booniehat_kopaska: H_HelmetB
	{
		scope=2;
		displayName="TNI Booniehat Kopaska";
		model="\A3\Characters_F\Common\booniehat";
		picture="\TNI\paa\icons\icon_booniehat_kopaska.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\bonniehat_kopaska.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=10;
			allowedSlots[]={801,901,701,605};
			uniformModel="\A3\Characters_F\Common\booniehat";
			hiddenSelections[]=
			{
				"camo"
			};
			modelSides[]={6};
			armor=1;
			passThrough=0;
		};
	};
	class TNI_booniehat_kopassus: H_HelmetB
	{
		scope=2;
		displayName="TNI Booniehat Kopassus";
		model="\A3\Characters_F\Common\booniehat";
		picture="\TNI\paa\icons\icon_booniehat_kopassus.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\booniehat_kopassus.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=10;
			allowedSlots[]={801,901,701,605};
			uniformModel="\A3\Characters_F\Common\booniehat";
			hiddenSelections[]=
			{
				"camo"
			};
			modelSides[]={6};
			armor=1;
			passThrough=0;
		};
	};
	class TNI_baret_kostrad: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Baret Kostrad";
		picture="\TNI\paa\icons\icon_kostrad_beret.paa";
		model="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\TNI_baret_kostrad.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\TNI_baret_kostrad.paa"
			};
		};
	};
	class TNI_baret_kopaska: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Baret Kopaska";
		picture="\TNI\paa\icons\icon_kopaska_beret.paa";
		model="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\TNI_baret_kopaska.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\TNI_baret_kopaska.paa"
			};
		};
	};
	class TNI_baret_kopassus: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Baret Kopassus";
		picture="\TNI\paa\icons\icon_kopassus_beret.paa";
		model="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\TNI_baret_kopasus.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\TNI_baret_kopasus.paa"
			};
		};
	};
	class TNI_baret_garuda: ItemCore
	{
		dlc="Indonesian_Mod";
		scope=2;
		weaponPoolAvailable=1;
		displayName="TNI Baret Garuda";
		picture="\TNI\paa\icons\icon_kopaska_beret.paa";
		model="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\TNI\paa\TNI_baret_garuda.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=5;
			uniformModel="\A3\characters_f_epb\BLUFOR\headgear_beret02.p3d";
			modelSides[]={3,1};
			armor="3*0.5";
			passThrough=0.80000001;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\TNI\paa\TNI_baret_garuda.paa"
			};
		};
	};
};
